sudo: required
services:
  - docker
language: generic
before_install:
  - docker login -u cmcquinn -p "$DOCKER_PASS"
jobs:
  include:
    - stage: "Base"
      script: 
      - "cd base ; ./build.sh"
      - docker push $REPO
    - stage: "Kernel and rootfs containers"
      script: "cd rootfs ; ./build.sh"
    - script: "cd kernel ; ./build.sh"
after_success:
- docker push $REPO
notifications:
  email:
    recipients:
      secure: M7u3y+h2jm0DwdGTab3eBeW7LM3pjkEGuKT50CxCT6IL6b4tMIdlaT3+bXMf4dy2hsGVORh3iZfEMlnRaGebNo5/80S1SyDDNU1Zm2Sv8HOgGeSmhp+nG1YGcj+Cjf6w2dJgD8zGcARDNA5NvdehYMa/EtYAOCJMHJ5lQpBWMqjJitBwBWMPULhrVn5EumSXuVMqgvPFAZnaQWJug8NeOHscxSaOuwCQawALNQA8Xz+XqYq5c6wGkCVK2C6Awy8lVF4p+cPCb7yjkf8ZL+UmcSqMxeI1YhjAX0Met7eAbwcRHiZqR23Oh5Iz1hwFnlqURZzMXbEAdho8xhX714r05aOGY7UvVC1apByLyeh8KsDrXfGQaF0Avzovvmd7ueAUuxxpzleWUwfQ4zOEGlx1ZRCJNpEO7Rdz4HkwgSknW7vf2tBNP4VZD0ptzpbShYreV9bjms6ZrDZQRnSZa2LmCu7MKbUxdTCQiHkkV300oaNGF6uNB1TiasThitf2xFKIr3Gg4fKXanyNLHtTOqQ/AYiWk5NZ3yHKWNCwa6DayJnLDzRDqn7zjOCZi5LtoxAa01Rz5YVVm1NCbTV14L4ZWW1ZER7qmQckTNvYQp8d/leVVrXRcysnsuc83lTEdpLgixSgQ7HhbXc0xJ3e/rHl5rDDFT6yc7ePJ5mlFCRshDI=
env:
  global:
    secure: vm5W10+kLP3BU4o5KGs3FIgBWyClbPNILQbIYtlUxLZhKjkIiRCW/MSkynQnOKKCPc7FmqBFyxm/J1Sjn1RSG3oM1sbgrLW/6BbpBmyJlESpBm9hy1f0vkeZDZiT8UDSPT9fwL8AV+aymo2/rRcduHPXO+bjjhC6lDdkaPqp6INO3HzxJX+Rx+T/6gKbXSTRrHeqXhZFd7SC1w+4h/VH+soFLwioztQo5JzYHWBNc+7bxzUPUbTBJ+zf0UK7fPDKXCl9sngL4D35KNjBGJpxIL1YW3ecHjkUXP3zppXjdtEgRJS7+UB10ITBeV4qKy54hijY/Hz3f6YJOsvIUyYQUWV0xz4v4S/OX4sVJKl1LXsOroKNeJsTxRvzyhcnfNmt0RzSR8RxtqdqkT+DzSWF4BSIRX7KbVoYbTAW08Ot1qyPtF35sox4UGNEknVzSVGIoYtUphfinIK7YTkqcb7sOYrwJxVMDMj2qJaknLtZBg7QsKS4nrjVrOI/M7hoiaIYPm3Eg7FpAMkAftATjxsoxPm95fHfQLOqyQzQHpFY2CJp5pSfRCKAzNtKwz8QLzBKd5MmTcm61GbsGWZIyrtVbvN0mxliFAuo1Tennnj7HCAF98pwBH2EOEan+IsYrKjXM97bwCo+vV1J3DvOykDfElZOA2t40QLix2ur8CIZ2sg=
